#!/bin/bash
#
# cloudera startup script for cloudera deamon
# chkconfig: 2345 99 20  
# description: start the cloudera deamon
#
# Source function library.
. /etc/init.d/functions

# Default variables
RETVAL=0

name="Cloudera"
start_path="/cloudera-init/run/start.sh"
stop_path="/cloudera-init/run/stop.sh"

start() {
  echo -n $"Starting $name..."
  nohup bash $start_path >> /cloudera-init/log/start.log 2>&1 &
  return $RETVAL
}

stop() {
  echo -n $"Stoping $name..."
  nohup bash $stop_path >> /cloudera-init/log/stop.log 2>&1 &
  return $RETVAL
}

restart() {
  echo -n $"Restarting $name..."
  bash $start_path >> /cloudera-init/log/restart.log 2>&1
  bash $stop_path >> /cloudera-init/log/restart.log 2>&1
  return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
esac

exit $RETVAL