#!/bin/sh  
#
# cloudera startup script for cloudera deamon
#
#
#chkconfig: 12345 80 20  
#description: start the cloudera deamon
#

# Source function library
. /etc/rc.d/init.d/functions

case "$1" in
start)
    echo "Starting Cloudera..."
    bash /cloudera-init/run/start.sh >> /cloudera-init/log/start.log 2>&1
    ;;

stop)
    echo "Stopping Cloudera..."
    bash /cloudera-init/run/stop.sh >> /cloudera-init/log/stop.log 2>&1
    ;;

restart)
    echo "Stopping Cloudera..."
    bash /cloudera-init/run/stop.sh >> /cloudera-init/log/stop.log 2>&1
    sleep 2
    echo
    echo "Starting Cloudera..."
    bash /cloudera-init/run/start.sh >> /cloudera-init/log/start.log 2>&1
    ;;

*)
    echo "Usage: $prog {start|stop|restart}"
    ;;
esac
exit 0
