#!/bin/sh  
  
#add for chkconfig  
#chkconfig: 2345 70 30  
#description: Cloudera Init
#processname: clouderaInit
# Source function library
. /etc/rc.d/init.d/functions

# init cloudera
bash /cloudera-init/run/start.sh >> /cloudera-init/log/init.log 2>&1;
